export default [
  'HTML5',
  'CSS3 / SASS / Animations',
  'JavaScript ES2017',
  'TypeScript & Babel',
  'React (SSR, Hooks)',
  'Redux',
  'Webpack',
  'Formik',
  'Storybook',
  'Styled Components',
  'Jest & Enzyme',
  'NodeJS & Express',
  'REST APIs & Microservices',
  'Backbone',
  'Grunt & Gulp',
  'Contentful CMS & Wordpress',
  'Cross Browser Optimization',
  'Browser Performance',
  'Atomic Design',
  'Agile',
  'Electron',
  'Markdown'
];
